### ISSUE TITLE
Задачите да могат да се виждат без регистрация 

### ISSUE THREAD

**Issue by MarinShalamanov** [pppepito86/arena#22]

**Comment by lyuben-todorov** [comment]
Не знам дали говоря празни глупости.
На ангюлар правата са му тук `src/main/webapp/app/entities/competition/competition.route.ts`.
Предполагам, че просто трябва да се разкарат всички `['ROLE_USER']`, които отговарят за competition. Ама също така тва не ми харесва:
``` 
    {
        path: 'catalog',
        redirectTo: 'catalog/1',
        pathMatch: 'full'
    },
```
хвърля грешка щото няма competition с id 1 в дев версията, или правите шантави работи с api-то.

За спринг трябва да се добави `.antMatchers("/api/competitions/**").permitAll()` в SecurityConfiguration-а. Като гледам правата за админи се хендълват правилно от RestController-а. 

За нещо по-дълбоко ли говориш?

**Comment by MarinShalamanov** [comment]
Предполагам нещо такова трябва да е. Но също и не трябва да може да се събмитва, ако не си логнат. Така, че и по UI-я трябва да се пипне разни неща - примерно да не се вижда полето за пращане на задача и вместо това да пише да влезеш. 

> redirectTo: 'catalog/1', 

До колкото си спомням, състезание 1 беше хардкоднато да е корена на йерархията от съсезания, която виждаш. Съгласен съм, че не е най-красивото. 

> няма competition с id 1 в дев версията,

Трябва да ти дадем dev dump на базата, ако ще цъкаш. 

> За нещо по-дълбоко ли говориш?

Не, този бъг го записах, за да го мислим, когато има време. Иначе това изискване идва от МОН / БАН, тъй като системата вече е част от https://infosbg.com/.

**Comment by lyuben-todorov** [comment]
Аха, тва с дървото е яко, няма проблем. Прати един дъмп по пощата (направих я public на гх профила ми) и ще го погледна тия дни.
