### ISSUE TITLE
Класирането се зарежда бавно

### ISSUE THREAD

**Issue by lyuben-todorov** [pppepito86/arena#25]
Още нямам дъмпа да видя дали наистина чегърта диска всеки път като се зареди `/#/catalog/1/standings`, но отнема около 4-5 секунди всеки път като зареди страницата. 

Гледам ползвате Liquibase за CacheManager?

findStandings в CompetitionService.java изглежда бая дебело с бая Join-ове.
Сега като гледам UserPoints не е entity и не се персиства, предполагам не може да бъде кеширано с @Cache? Може би да се сложи един @Cachable?

**Comment by MarinShalamanov** [comment]
В крайна сметка обхожда всички събмити, за да сметне класирането, което не
е яко, защото става все по-бавно с времето. Да, трябва цялото класиране да
са кешира и да се ъпдейтва по някакъв начин. Бих бил окей с нeщо, което на
всеки Х минути го преизчислява и сторва в мемори и когато user-а го поиска
го вади от там. Но със сиг не е ок да се смята като го поиска потребител.
Понякога тая заявка отнема и 30 сек. Трябва да разгледам кода, за да ти
кажа за UserPoints.  Liquibase е за миграциите?

**Comment by lyuben-todorov** [comment]
Толкова съм гледал, той просто ползва CacheManager.

Може би лесно решение е в `CacheConfiguration.java` да се добави това?
```java
cm.createCache(com.olimpiici.arena.domain.UserPoints.class.getName(), jcacheConfiguration);
```
Ще ги тествам тия неща по-късно.

**Comment by lyuben-todorov** [comment]
Разбрах горе-долу кво се случва. 
```java
    @Bean
    public JCacheManagerCustomizer cacheManagerCustomizer() {
        return cm -> {

            cm.createCache(com.olimpiici.arena.repository.UserRepository.USERS_BY_LOGIN_CACHE, jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.repository.UserRepository.USERS_BY_EMAIL_CACHE, jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.User.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.Authority.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.User.class.getName() + ".authorities", jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.Competition.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.Problem.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.CompetitionProblem.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.Submission.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.TagCollection.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.Tag.class.getName(), jcacheConfiguration);
            cm.createCache(com.olimpiici.arena.domain.TagCollectionTag.class.getName(), jcacheConfiguration);

            cm.createCache(com.olimpiici.arena.domain.UserPoints.class.getName(), jcacheConfiguration);

            // jhipster-needle-ehcache-add-entry
        };
    }
```
Целия този bean е безполезен ако няма `@Cachеable( cacheNames = ...)` над някой метод като cacheNames трябва да е някой вече създаден cache. В момента се кешират само два метода в целия проект на ниво Repository интерфейс.

В момента мисля просто да кеширам на ниво метод и с ttl 3 минути? Не е много хубаво но е 2 реда и поне предотвратява да умре сървъра ако 5 човека цъкнат едновременно (на мен ми дава heap space error като пусна 6-7 паралелни заявки).

**Comment by lyuben-todorov** [comment]
ето и диф https://github.com/pppepito86/arena/compare/master...lyuben-todorov:25-speed-up-standings

**Comment by MarinShalamanov** [comment]
Това  ще върши някаква работа, но все пак се притеснявам, че най-вероятно
всеки който рекуества пак ще трябва да чака. Тоест предполагам че рядко
имаме повече от 1 рекуест за класирнето на 3 мин мин. Какво мислиш да има и
един @Scheduled, който update-ва кеша на всеки три минути?

**Comment by lyuben-todorov** [comment]
Ау тва е 3000 айкю. Тъкмо мислех някви други схеми.

**Comment by lyuben-todorov** [comment]
#27
