### ISSUE TITLE
Internal server error when I click "Класиране"

### ISSUE THREAD

**Issue by MarinShalamanov** [pppepito86/arena#37]

**Comment by MarinShalamanov** [comment]
Root cause is java.lang.OutOfMemoryError: Java heap space

**Comment by lyuben-todorov** [comment]
Opa

**Comment by MarinShalamanov** [comment]
Това не е от твойте промени. Тях ги ревъртнахме по-отдавна защото сървъра
умираше без да си казва защо :д Но двете може да са свързани. Така че скоро
мога ги пусна пак да видим дали се е отправило.
